# Generated by Django 4.1.3 on 2023-01-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bannerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_perfume', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='description_product',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
